### ISSUE TITLE
Home page poll - Submit a poll response

### ISSUE THREAD

**Issue by Huddy2022** [Huddy2022/love-running#1]
In order to **provide my opinion** with regards to a certain **running topic or event as a user**, I can **select and submit an answer from the poll**

Acceptance criteria:

- The option should be provided with an input
- The option should appear above the submit button
- The poll should say thank you after submitting

# Tasks:

- [ ] Update the website to include an input using html
- [ ] Use css to place the poll input bar
- [ ] Create a thank you message in css after submitting
