### ISSUE TITLE
Home page poll - Publish a poll

### ISSUE THREAD

**Issue by Huddy2022** [Huddy2022/love-running#2]
In order to **collect users feedback** as a **administrator**, I can **publish a poll**

Acceptance criteria:

- The option should be provided as a checkbox
- The checkbox should be provided as default
- The input can include the user's details

# Tasks:

- [ ] Update the website to include html and css as a checkbox
- [ ] Add checked in the html to class as default
- [ ] Create an input for the user to add their details
